[package]
name = "interception-sys"
description = "FFI bindings for Interception"
version = "0.1.0"
authors = ["Joe Kaushal <joe.kaushal@gmail.com>"]
edition = "2018"
repository = "https://github.com/bozbez/interception-sys"
license = "LGPL-3.0"
